#!/usr/bin/env python3
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def apply(name, pairs):
    path = ROOT / name
    text = path.read_text()
    for a, b in pairs:
        if a not in text:
            print('MISSING', name, a[:100].replace('\n',' '))
        else:
            text = text.replace(a, b)
    path.write_text(text)
    print('ok', name)

apply('lifestyle.html', [
('<p class="hero-eyebrow reveal">Beyond the move</p>',
 '<p class="hero-eyebrow reveal" data-i18n="lifestyle.eyebrow">Beyond the move</p>'),
('<h1 class="page-hero-title reveal">Lifestyle · <em>travel &amp; accommodation</em></h1>',
 '<h1 class="page-hero-title reveal" data-i18n-html="lifestyle.heroHtml">Lifestyle · <em>travel &amp; accommodation</em></h1>'),
('<nav class="service-nav service-nav-lifestyle reveal" aria-label="Lifestyle categories">',
 '<nav class="service-nav service-nav-lifestyle reveal" aria-label="Lifestyle categories" data-i18n-aria="lifestyle.ariaCats">'),
('<a href="#hidden-gems" class="service-nav-link">Hotels &amp; Hidden gems</a>',
 '<a href="#hidden-gems" class="service-nav-link" data-i18n="lifestyle.navHotels">Hotels &amp; Hidden gems</a>'),
('<a href="#holiday-homes" class="service-nav-link">Holiday homes</a>',
 '<a href="#holiday-homes" class="service-nav-link" data-i18n="lifestyle.navHomes">Holiday homes</a>'),
('<a href="#travel" class="service-nav-link">Commercial flights</a>',
 '<a href="#travel" class="service-nav-link" data-i18n="lifestyle.navFlights">Commercial flights</a>'),
('<a href="#private-jet" class="service-nav-link">Private jet</a>',
 '<a href="#private-jet" class="service-nav-link" data-i18n="lifestyle.navJet">Private jet</a>'),
('<a href="#yacht" class="service-nav-link">Yacht charter</a>',
 '<a href="#yacht" class="service-nav-link" data-i18n="lifestyle.navYacht">Yacht charter</a>'),
('<a href="#swiss-villages" class="service-nav-link">Swiss villages</a>',
 '<a href="#swiss-villages" class="service-nav-link" data-i18n="lifestyle.navVillages">Swiss villages</a>'),
('<div class="section-label">Hotels &amp; Hidden gems</div>',
 '<div class="section-label" data-i18n="lifestyle.navHotels">Hotels &amp; Hidden gems</div>'),
('<h2 class="section-title">Distinctive stays,<br><em>not the ordinary</em></h2>',
 '<h2 class="section-title" data-i18n-html="lifestyle.hotelsTitle">Distinctive stays,<br><em>not the ordinary</em></h2>'),
('<p class="body-text">We source boutique hotels and discreet addresses that match your taste — intimate properties and design-led houses away from the mass-market circuit. Most of the properties have been vetted personally.</p>',
 '<p class="body-text" data-i18n="lifestyle.hotelsLead">We source boutique hotels and discreet addresses that match your taste — intimate properties and design-led houses away from the mass-market circuit. Most of the properties have been vetted personally.</p>'),
('<li>Curated boutique and design hotels worldwide</li>',
 '<li data-i18n="lifestyle.hotels1">Curated boutique and design hotels worldwide</li>'),
('<li>Off-radar properties for privacy and character</li>',
 '<li data-i18n="lifestyle.hotels2">Off-radar properties for privacy and character</li>'),
('<li>Preferred rates and availability through our travel partners where available</li>',
 '<li data-i18n="lifestyle.hotels3">Preferred rates and availability through our travel partners where available</li>'),
('<a href="travel-contact.html" class="btn btn-primary">Contact Tarja</a>',
 '<a href="travel-contact.html" class="btn btn-primary" data-i18n="lifestyle.contactTarja">Contact Tarja</a>'),
('<div class="section-label">Exclusive holiday homes</div>',
 '<div class="section-label" data-i18n="lifestyle.homesLabel">Exclusive holiday homes</div>'),
('<h2 class="section-title">Villas &amp; residences<br><em>for discerning clients</em></h2>',
 '<h2 class="section-title" data-i18n-html="lifestyle.homesTitle">Villas &amp; residences<br><em>for discerning clients</em></h2>'),
('<p class="body-text">Exclusive holiday homes and seasonal residences — for short stays or longer seasons — introduced privately to our clients. Owned by our clients for our clients.</p>',
 '<p class="body-text" data-i18n="lifestyle.homesLead">Exclusive holiday homes and seasonal residences — for short stays or longer seasons — introduced privately to our clients. Owned by our clients for our clients.</p>'),
('<li>Villas and penthouses for holiday and seasonal rental</li>',
 '<li data-i18n="lifestyle.homes1">Villas and penthouses for holiday and seasonal rental</li>'),
('<li>Mediterranean and alpine destinations, selected for quality and discretion</li>',
 '<li data-i18n="lifestyle.homes2">Mediterranean and alpine destinations, selected for quality and discretion</li>'),
('<li>Full documentation and introductions on request</li>',
 '<li data-i18n="lifestyle.homes3">Full documentation and introductions on request</li>'),
('<p class="body-text">Current opportunities we can present:</p>',
 '<p class="body-text" data-i18n="lifestyle.homesCurrent">Current opportunities we can present:</p>'),
('<span>Greece · Brochure</span>',
 '<span data-i18n="lifestyle.brochure">Greece · Brochure</span>'),
('<span>Marbella · Golden Mile · Gallery</span>',
 '<span data-i18n="lifestyle.gallery">Marbella · Golden Mile · Gallery</span>'),
('<span class="lifestyle-doc-action">Open</span>',
 '<span class="lifestyle-doc-action" data-i18n="common.open">Open</span>'),
('<strong>Marbella film</strong>',
 '<strong data-i18n="lifestyle.film">Marbella film</strong>'),
('<span>Terrazas Penthouse · Video tour</span>',
 '<span data-i18n="lifestyle.videoTour">Terrazas Penthouse · Video tour</span>'),
('<span class="lifestyle-doc-action">Play</span>',
 '<span class="lifestyle-doc-action" data-i18n="common.play">Play</span>'),
('<a href="contact.html" class="btn btn-primary">Enquire about a residence</a>',
 '<a href="contact.html" class="btn btn-primary" data-i18n="lifestyle.enquireHome">Enquire about a residence</a>'),
('<div class="section-label">Commercial flights</div>',
 '<div class="section-label" data-i18n="lifestyle.navFlights">Commercial flights</div>'),
('<h2 class="section-title">Commercial flights,<br><em>arranged for you</em></h2>',
 '<h2 class="section-title" data-i18n-html="lifestyle.flightsTitle">Commercial flights,<br><em>arranged for you</em></h2>'),
('<p class="body-text">We arrange international travel with the same care as your relocation — itineraries, ticketing and logistics handled end to end.</p>',
 '<p class="body-text" data-i18n="lifestyle.flightsLead">We arrange international travel with the same care as your relocation — itineraries, ticketing and logistics handled end to end.</p>'),
('<li>IATA member — accredited travel arrangements</li>',
 '<li data-i18n="lifestyle.flights1">IATA member — accredited travel arrangements</li>'),
('<li>Complex multi-city and family itineraries</li>',
 '<li data-i18n="lifestyle.flights2">Complex multi-city and family itineraries</li>'),
('<li>Business and leisure travel coordinated with your schedule</li>',
 '<li data-i18n="lifestyle.flights3">Business and leisure travel coordinated with your schedule</li>'),
('<li>Transfers, hotels and ground logistics aligned with your journey</li>',
 '<li data-i18n="lifestyle.flights4">Transfers, hotels and ground logistics aligned with your journey</li>'),
('<h2 class="section-title">Private aviation,<br><em>on your terms</em></h2>',
 '<h2 class="section-title" data-i18n-html="lifestyle.jetTitle">Private aviation,<br><em>on your terms</em></h2>'),
('<p class="body-text">When time and privacy matter, we coordinate private jet charters — empty legs, on-demand flights and tailored routing through trusted aviation partners.</p>',
 '<p class="body-text" data-i18n="lifestyle.jetLead">When time and privacy matter, we coordinate private jet charters — empty legs, on-demand flights and tailored routing through trusted aviation partners.</p>'),
('<li>On-demand private jet charter</li>',
 '<li data-i18n="lifestyle.jet1">On-demand private jet charter</li>'),
('<li>Empty-leg opportunities when suitable</li>',
 '<li data-i18n="lifestyle.jet2">Empty-leg opportunities when suitable</li>'),
('<li>Crew, catering and ground handling coordinated</li>',
 '<li data-i18n="lifestyle.jet3">Crew, catering and ground handling coordinated</li>'),
('<li>Confidential introductions to vetted operators</li>',
 '<li data-i18n="lifestyle.jet4">Confidential introductions to vetted operators</li>'),
('<a href="contact.html" class="btn btn-primary">Request a jet charter</a>',
 '<a href="contact.html" class="btn btn-primary" data-i18n="lifestyle.jetCta">Request a jet charter</a>'),
('<div class="section-label">Yacht chartering</div>',
 '<div class="section-label" data-i18n="lifestyle.yachtLabel">Yacht chartering</div>'),
('<h2 class="section-title">On the water,<br><em>in style</em></h2>',
 '<h2 class="section-title" data-i18n-html="lifestyle.yachtTitle">On the water,<br><em>in style</em></h2>'),
('<p class="body-text">Yacht charters for Mediterranean and nearby coasts — motor and sailing — arranged with captains, crew and itineraries that fit your party.</p>',
 '<p class="body-text" data-i18n="lifestyle.yachtLead">Yacht charters for Mediterranean and nearby coasts — motor and sailing — arranged with captains, crew and itineraries that fit your party.</p>'),
('<li>Motor yacht and sailing yacht charter</li>',
 '<li data-i18n="lifestyle.yacht1">Motor yacht and sailing yacht charter</li>'),
('<li>Crewed charters for holidays and incentives</li>',
 '<li data-i18n="lifestyle.yacht2">Crewed charters for holidays and incentives</li>'),
('<li>Itinerary, berth and provisioning support</li>',
 '<li data-i18n="lifestyle.yacht3">Itinerary, berth and provisioning support</li>'),
('<li>Introductions to trusted yacht brokers and operators</li>',
 '<li data-i18n="lifestyle.yacht4">Introductions to trusted yacht brokers and operators</li>'),
('<div class="section-label">Destinations</div>',
 '<div class="section-label" data-i18n="lifestyle.destLabel">Destinations</div>'),
('<p class="body-text">Chartering a yacht opens the door to endless possibilities: simply tell us where you dream of sailing, and we\'ll match you with the perfect vessel to get you there.</p>',
 '<p class="body-text" data-i18n="lifestyle.dest1">Chartering a yacht opens the door to endless possibilities: simply tell us where you dream of sailing, and we\'ll match you with the perfect vessel to get you there.</p>'),
('<p class="body-text">Are you drawn to breathtaking coastlines, timeless historic ports, or the glamour of the world\'s most exclusive hotspots? Let our curated destinations and signature itineraries spark your imagination. Once you\'ve settled on a cruising region, our team will design a bespoke voyage tailored entirely to your tastes and pace. Explore the places you\'ve always dreamed of — we\'ll bring that dream to life.</p>',
 '<p class="body-text" data-i18n="lifestyle.dest2">Are you drawn to breathtaking coastlines, timeless historic ports, or the glamour of the world\'s most exclusive hotspots? Let our curated destinations and signature itineraries spark your imagination. Once you\'ve settled on a cruising region, our team will design a bespoke voyage tailored entirely to your tastes and pace. Explore the places you\'ve always dreamed of — we\'ll bring that dream to life.</p>'),
('<a href="contact.html" class="btn btn-primary">Enquire about a yacht</a>',
 '<a href="contact.html" class="btn btn-primary" data-i18n="lifestyle.yachtCta">Enquire about a yacht</a>'),
('<div class="section-label">Swiss villages</div>',
 '<div class="section-label" data-i18n="lifestyle.navVillages">Swiss villages</div>'),
('<h2 class="section-title">Switzerland’s most<br><em>beautiful villages</em></h2>',
 '<h2 class="section-title" data-i18n-html="lifestyle.villagesTitle">Switzerland’s most<br><em>beautiful villages</em></h2>'),
('<p class="body-text">Lakeside towns and alpine hamlets that define living and travelling in Switzerland — inspiration for stays, weekends and a life well settled.</p>',
 '<p class="body-text" data-i18n="lifestyle.villagesLead">Lakeside towns and alpine hamlets that define living and travelling in Switzerland — inspiration for stays, weekends and a life well settled.</p>'),
('<li>Curated destinations across Ticino and beyond</li>',
 '<li data-i18n="lifestyle.villages1">Curated destinations across Ticino and beyond</li>'),
('<li>Authentic villages for weekends and longer stays</li>',
 '<li data-i18n="lifestyle.villages2">Authentic villages for weekends and longer stays</li>'),
('<li>Introductions via Best Swiss Villages</li>',
 '<li data-i18n="lifestyle.villages3">Introductions via Best Swiss Villages</li>'),
('<li>Official map and guidebooks available to our clients at favourable prices</li>',
 '<li data-i18n="lifestyle.villages4">Official map and guidebooks available to our clients at favourable prices</li>'),
('<p class="body-text lifestyle-sv-note">Through our partnership with Best Swiss Villages, we can offer the Michelin map and selected guidebooks at favourable client prices.</p>',
 '<p class="body-text lifestyle-sv-note" data-i18n="lifestyle.svNote">Through our partnership with Best Swiss Villages, we can offer the Michelin map and selected guidebooks at favourable client prices.</p>'),
('<span>Official map · FR · DE · EN</span>',
 '<span data-i18n="lifestyle.mapMeta">Official map · FR · DE · EN</span>'),
('<span>Official guidebook · IT</span>',
 '<span data-i18n="lifestyle.borghiMeta">Official guidebook · IT</span>'),
('<span>The Switzerland I love · FR · DE · EN</span>',
 '<span data-i18n="lifestyle.loveMeta">The Switzerland I love · FR · DE · EN</span>'),
('                View photo gallery',
 '                <span data-i18n="lifestyle.galleryCta">View photo gallery</span>'),
('<a href="shop-swiss-villages.html" class="btn btn-primary">Order map &amp; books</a>',
 '<a href="shop-swiss-villages.html" class="btn btn-primary" data-i18n="lifestyle.orderCta">Order map &amp; books</a>'),
('<h2 class="section-title">Let\'s get<br><em>in touch</em></h2>',
 '<h2 class="section-title" data-i18n-html="common.letsTouchHtml">Let\'s get<br><em>in touch</em></h2>'),
('<p class="section-lead">Tell us how you wish to travel or stay — we respond discreetly and personally.</p>',
 '<p class="section-lead" data-i18n="lifestyle.ctaLead">Tell us how you wish to travel or stay — we respond discreetly and personally.</p>'),
('<a href="contact.html" class="btn btn-primary">Contact us</a>',
 '<a href="contact.html" class="btn btn-primary" data-i18n="common.contactUs">Contact us</a>'),
('<button type="button" class="video-modal-close" data-video-close aria-label="Close video">',
 '<button type="button" class="video-modal-close" data-video-close aria-label="Close video" data-i18n-aria="lifestyle.closeVideo">'),
('<h2 id="swiss-gallery-title">Swiss villages</h2>',
 '<h2 id="swiss-gallery-title" data-i18n="lifestyle.galleryTitle">Swiss villages</h2>'),
('<button type="button" class="gallery-modal-close" data-gallery-close aria-label="Close gallery">',
 '<button type="button" class="gallery-modal-close" data-gallery-close aria-label="Close gallery" data-i18n-aria="lifestyle.closeGallery">'),
('<button type="button" class="gallery-nav gallery-nav-prev" data-gallery-prev aria-label="Previous photo">',
 '<button type="button" class="gallery-nav gallery-nav-prev" data-gallery-prev aria-label="Previous photo" data-i18n-aria="common.previous">'),
('<button type="button" class="gallery-nav gallery-nav-next" data-gallery-next aria-label="Next photo">',
 '<button type="button" class="gallery-nav gallery-nav-next" data-gallery-next aria-label="Next photo" data-i18n-aria="common.next">'),
])
